eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8810/eureka/
server:
  tomcat:
    uri-encoding: UTF-8
  port: 10002
#  servlet:
#    context-path: /gbq_consumer
spring:
  main:
    allow-bean-definition-overriding: true  #避免相同名字的Feign注册会导致重复注册
  application:
    name: consumer-feign
