eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8802
  servlet:
    context-path: /gbq_consumer
spring:
  application:
    name: consumer
