server:
  port: 12000
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8800/eureka/,http://eureka02:8810/eureka/


turbine:
  aggregator:
    # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    clusterConfig: default
    # 配置Eureka中的serviceId列表，表明监控哪些服务
  appConfig: consumer_ribbon_hystrix,consumer_feign_hystrix
    #设置监控的表达式，通过此表达式表示要获取监控信息名称
  clusterNameExpression: new String("default")

spring:
  application:
    name: service-turbine
  main:
    allow-bean-definition-overriding: true